# Day 14:  5 March Thursday 
## Pandas Library

In [3]:
## Pandas Library
import pandas as pd
import numpy as np

In [3]:
## Series form
s1 = pd.Series([2, 3, 4, 5, 6, 7])
s2 = pd.Series([1, 2, 3, 4, 5, 6], index=['A', 'B', 'C', 'D', 'E', 'F'])
s3 = pd.Series({'A': 12, 'B': 14, 'C': 16})
print(s1.values)
print(s2.index)
print(s2.dtype)
print(s2.values)
print(s3)

[2 3 4 5 6 7]
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
int64
[1 2 3 4 5 6]
A    12
B    14
C    16
dtype: int64

In [4]:
# Task :Create a Series of your favorite movies with years as index
series = pd.Series(['Horror Story', 'Haunted', 'Dilwale', 'Tik Tik Tik', 'Theri'], index=['a', 'b', 'c', 'd', 'e'])
print(series)

a    Horror Story
b         Haunted
c         Dilwale
d     Tik Tik Tik
e           Theri
dtype: object

In [5]:
## Dataframe 
df = pd.DataFrame({
    'Name': ['Shaiza', 'Amna', 'Noor', 'Mehak', 'Moazma', 'Sawera', 'Aiman'],
    'Age': [19, 20, 19, 19, 20, 19, 19],
    'Salary': [70000, 65000, 68000, 67000, 72000, 74000, 70000],
    'Department': ['AI Developer', 'UI/UX Designer', 'Web Developer', 'Digital Marketing Expert', 'Game Developer', 'Brand Ambassador', 'Prompt Engineer']
})

df.shape

(7, 4)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        7 non-null      object
 1   Age         7 non-null      int64
 2   Salary      7 non-null      int64
 3   Department  7 non-null      object
dtypes: int64(2), object(2)
memory usage: 356.0+ bytes

In [7]:
df.describe()

             Age        Salary
count   7.000000      7.000000
mean   19.285714  69428.571429
std     0.487950   3047.247001
min    19.000000  65000.000000
25%    19.000000  67500.000000
50%    19.000000  70000.000000
75%    19.500000  71000.000000
max    20.000000  74000.000000

In [8]:
print(df['Name'])

0    Shaiza
1      Amna
2      Noor
3     Mehak
4    Moazma
5    Sawera
6     Aiman
Name: Name, dtype: object

In [9]:
print(df[['Department', 'Salary']])

                 Department  Salary
0              AI Developer   70000
1            UI/UX Designer   65000
2             Web Developer   68000
3  Digital Marketing Expert   67000
4            Game Developer   72000
5          Brand Ambassador   74000
6           Prompt Engineer   70000

In [10]:
print(df.iloc[0])

Name                Shaiza
Age                     19
Salary               70000
Department    AI Developer
Name: 0, dtype: object

In [11]:
print(df.loc[0])

Name                Shaiza
Age                     19
Salary               70000
Department    AI Developer
Name: 0, dtype: object

In [12]:
print(df.iloc[1])

Name                    Amna
Age                       20
Salary                 65000
Department    UI/UX Designer
Name: 1, dtype: object

In [13]:
print(df.iloc[1:3])

   Name  Age  Salary      Department
1  Amna   20   65000  UI/UX Designer
2  Noor   19   68000   Web Developer

In [14]:
print(df[df['Age']> 19])

     Name  Age  Salary      Department
1    Amna   20   65000  UI/UX Designer
4  Moazma   20   72000  Game Developer

In [15]:
print(df[(df['Age'] < 20) & (df['Department'] == 'AI Developer')])

     Name  Age  Salary    Department
0  Shaiza   19   70000  AI Developer

In [16]:
df.head(3)

     Name  Age  Salary      Department
0  Shaiza   19   70000    AI Developer
1    Amna   20   65000  UI/UX Designer
2    Noor   19   68000   Web Developer

In [26]:
df.tail(3)

     Name  Age  Salary        Department
4  Moazma   20   72000    Game Developer
5  Sawera   19   74000  Brand Ambassador
6   Aiman   19   70000   Prompt Engineer

In [27]:
print(df['Department'].unique())

['AI Developer' 'UI/UX Designer' 'Web Developer'
 'Digital Marketing Expert' 'Game Developer' 'Brand Ambassador'
 'Prompt Engineer']

In [28]:
print(df['Salary'].nunique())

6

In [29]:
print(df['Department'].value_counts())

Department
AI Developer                1
UI/UX Designer              1
Web Developer               1
Digital Marketing Expert    1
Game Developer              1
Brand Ambassador            1
Prompt Engineer             1
Name: count, dtype: int64

In [30]:
print(df['Age'].value_counts())

Age
19    5
20    2
Name: count, dtype: int64

In [31]:
df_sorted_age = df.sort_values('Age', ascending = False)
df_sorted_age

     Name  Age  Salary                Department
1    Amna   20   65000            UI/UX Designer
4  Moazma   20   72000            Game Developer
0  Shaiza   19   70000              AI Developer
2    Noor   19   68000             Web Developer
3   Mehak   19   67000  Digital Marketing Expert
5  Sawera   19   74000          Brand Ambassador
6   Aiman   19   70000           Prompt Engineer

In [32]:
print(df.columns.tolist())

['Name', 'Age', 'Salary', 'Department']

In [33]:
print(df.index.tolist())

[0, 1, 2, 3, 4, 5, 6]

In [34]:
df.isnull()

    Name    Age  Salary  Department
0  False  False   False       False
1  False  False   False       False
2  False  False   False       False
3  False  False   False       False
4  False  False   False       False
5  False  False   False       False
6  False  False   False       False

In [35]:
df.isnull().sum()

Name          0
Age           0
Salary        0
Department    0
dtype: int64

In [36]:
df.isnull().sum().sum()

np.int64(0)

In [37]:
df.drop([1, 2])

     Name  Age  Salary                Department
0  Shaiza   19   70000              AI Developer
3   Mehak   19   67000  Digital Marketing Expert
4  Moazma   20   72000            Game Developer
5  Sawera   19   74000          Brand Ambassador
6   Aiman   19   70000           Prompt Engineer

# Day 15: 6 March Friday
## Pandas Library Practice

In [38]:
data = pd.DataFrame({
    'Name': ['Azan', 'Saima', 'Aslam', 'Azlan', 'Arsalan', 'Ayesha', 'Aroma', 'Zainab', 'Zufra', 'Zaisha'],
    'ID':[2001, 2022, 3030, 3242, 3678, 4325, 6543, 8965, 9876, 5432],
    'Age': [18, np.nan, 20, 22, 25 ,28, np.nan, 23, 28, np.nan],
    'Gender': ['Male', 'Female', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female'],
    'City': ['Lahore', np.nan, 'Islamabad', 'Gujrat', np.nan, 'Gujranwala', 'Faislabad', np.nan, 'Multan', np.nan],
    'Role': ['CFO', np.nan, 'HR', np.nan, 'Marketing Manager', 'Sales Executive', np.nan, 'Product Manager', 'IT Specialist', np.nan],
    'Salary': [50000, 60000, 45000, 55000, np.nan, 63000, 70000, 65000, np.nan, 48000],
    'Joining Date': ['March 2024', 'May 2024', 'July 2025', 'Sep 2023', np.nan, 'Aug 2022', 'Jan 2021', 'Feb 2026',np.nan, 'Dec 2024'],
    'Experience': ['4 years', '3 years', '2 years', '1 year', '5 years', '7 years', np.nan, '2.5 years', '3.5 years', '5.5 years'],
    'Performance Rating': ['80%', '85%', '70%', '75%', '65%', np.nan, '90%', '95%', np.nan, '92%']    
})
data

,Name,ID,Age,Gender,City,Role,Salary,Joining Date,Experience,Performance Rating
0,Azan,2001,18.0,Male,Lahore,CFO,50000.0,March 2024,4 years,80%
1,Saima,2022,NaN,Female,NaN,NaN,60000.0,May 2024,3 years,85%
2,Aslam,3030,20.0,Male,Islamabad,HR,45000.0,July 2025,2 years,70%
3,Azlan,3242,22.0,Male,Gujrat,NaN,55000.0,Sep 2023,1 year,75%
4,Arsalan,3678,25.0,Male,NaN,Marketing Manager,NaN,NaN,5 years,65%
5,Ayesha,4325,28.0,Female,Gujranwala,Sales Executive,63000.0,Aug 2022,7 years,NaN
6,Aroma,6543,NaN,Female,Faislabad,NaN,70000.0,Jan 2021,NaN,90%
7,Zainab,8965,23.0,Female,NaN,Product Manager,65000.0,Feb 2026,2.5 years,95%
8,Zufra,9876,28.0,Female,Multan,IT Specialist,NaN,NaN,3.5 years,NaN
9,Zaisha,5432,NaN,Female,NaN,NaN,48000.0,Dec 2024,5.5 years,92%

In [39]:
data.isnull()

,Name,ID,Age,Gender,City,Role,Salary,Joining Date,Experience,Performance Rating
0,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,True,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,True,False,True,True,False,False
5,False,False,False,False,False,False,False,False,False,True
6,False,False,True,False,False,True,False,False,True,False
7,False,False,False,False,True,False,False,False,False,False
8,False,False,False,False,False,False,True,True,False,True
9,False,False,True,False,True,True,False,False,False,False

In [40]:
data.isnull().sum()

Name                  0
ID                    0
Age                   3
Gender                0
City                  4
Role                  4
Salary                2
Joining Date          2
Experience            1
Performance Rating    2
dtype: int64

In [41]:
data.isnull().sum().sum()

np.int64(18)

In [49]:
data.ffill(inplace = True)
data

,Employee_Name,ID,Age,Gender,City,Role,Salary,Joining Date,Experience,Performance Rating
0,Azan,2001,18.0,Male,Lahore,CFO,50000.0,March 2024,4 years,80%
1,Saima,2022,18.0,Female,Lahore,CFO,60000.0,May 2024,3 years,85%
2,Aslam,3030,20.0,Male,Islamabad,HR,45000.0,July 2025,2 years,70%
3,Azlan,3242,22.0,Male,Gujrat,HR,55000.0,Sep 2023,1 year,75%
4,Arsalan,3678,25.0,Male,Gujrat,Marketing Manager,55000.0,Sep 2023,5 years,65%
5,Ayesha,4325,28.0,Female,Gujranwala,Sales Executive,63000.0,Aug 2022,7 years,65%
6,Aroma,6543,28.0,Female,Faislabad,Sales Executive,70000.0,Jan 2021,7 years,90%
7,Zainab,8965,23.0,Female,Faislabad,Product Manager,65000.0,Feb 2026,2.5 years,95%
8,Zufra,9876,28.0,Female,Multan,IT Specialist,65000.0,Feb 2026,3.5 years,95%
9,Zaisha,5432,28.0,Female,Multan,IT Specialist,48000.0,Dec 2024,5.5 years,92%

In [48]:
data.bfill(inplace = True)
data

,Employee_Name,ID,Age,Gender,City,Role,Salary,Joining Date,Experience,Performance Rating
0,Azan,2001,18.0,Male,Lahore,CFO,50000.0,March 2024,4 years,80%
1,Saima,2022,18.0,Female,Lahore,CFO,60000.0,May 2024,3 years,85%
2,Aslam,3030,20.0,Male,Islamabad,HR,45000.0,July 2025,2 years,70%
3,Azlan,3242,22.0,Male,Gujrat,HR,55000.0,Sep 2023,1 year,75%
4,Arsalan,3678,25.0,Male,Gujrat,Marketing Manager,55000.0,Sep 2023,5 years,65%
5,Ayesha,4325,28.0,Female,Gujranwala,Sales Executive,63000.0,Aug 2022,7 years,65%
6,Aroma,6543,28.0,Female,Faislabad,Sales Executive,70000.0,Jan 2021,7 years,90%
7,Zainab,8965,23.0,Female,Faislabad,Product Manager,65000.0,Feb 2026,2.5 years,95%
8,Zufra,9876,28.0,Female,Multan,IT Specialist,65000.0,Feb 2026,3.5 years,95%
9,Zaisha,5432,28.0,Female,Multan,IT Specialist,48000.0,Dec 2024,5.5 years,92%

In [46]:
data.rename(columns ={'Name': 'Employee_Name'}, inplace = True)
data

,Employee_Name,ID,Age,Gender,City,Role,Salary,Joining Date,Experience,Performance Rating
0,Azan,2001,18.0,Male,Lahore,CFO,50000.0,March 2024,4 years,80%
1,Saima,2022,18.0,Female,Lahore,CFO,60000.0,May 2024,3 years,85%
2,Aslam,3030,20.0,Male,Islamabad,HR,45000.0,July 2025,2 years,70%
3,Azlan,3242,22.0,Male,Gujrat,HR,55000.0,Sep 2023,1 year,75%
4,Arsalan,3678,25.0,Male,Gujrat,Marketing Manager,55000.0,Sep 2023,5 years,65%
5,Ayesha,4325,28.0,Female,Gujranwala,Sales Executive,63000.0,Aug 2022,7 years,65%
6,Aroma,6543,28.0,Female,Faislabad,Sales Executive,70000.0,Jan 2021,7 years,90%
7,Zainab,8965,23.0,Female,Faislabad,Product Manager,65000.0,Feb 2026,2.5 years,95%
8,Zufra,9876,28.0,Female,Multan,IT Specialist,65000.0,Feb 2026,3.5 years,95%
9,Zaisha,5432,28.0,Female,Multan,IT Specialist,48000.0,Dec 2024,5.5 years,92%

In [4]:
data1 = [
    ['Hoor', 32 , 20 , 'BSCS', 3.5, 'Lahore'],
    ['Aina', 24, 21, 'BSIT', 3.7, 'Gujranwala'],
    ['Umaima', 19, 22, 'BS English', 3.4, 'Sialkot'],
    ['Fahad', 28, 21, 'BS Pychology', 3.15, 'Islamabad'],
    ['Hashir', 35, 23, 'BS Zoology', 3.45, 'Gujrat'],
    ['Talha', 21, 20, 'BS Physics', 3.2, 'Sahiwaal'],
    ['Noor', 18, 19, 'BS Artificial Intelligence', 3.56, 'Chakwal'],
    ['Lubaina', 27, 20, 'BS Chemistry', 3.7, 'Azad Kashmir'],
    ['Ayesha', 11, 19, 'BS Cybersecurity', 3.8, 'Mianwali']
]

columns = ["Name", "Roll_No", "Age", "Department", "CGPA", "City"]
data2 = pd.DataFrame(data1, columns=columns)
data2

      Name  Roll_No  Age                  Department  CGPA          City
0     Hoor       32   20                        BSCS  3.50        Lahore
1     Aina       24   21                        BSIT  3.70    Gujranwala
2   Umaima       19   22                  BS English  3.40       Sialkot
3    Fahad       28   21                BS Pychology  3.15     Islamabad
4   Hashir       35   23                  BS Zoology  3.45        Gujrat
5    Talha       21   20                  BS Physics  3.20      Sahiwaal
6     Noor       18   19  BS Artificial Intelligence  3.56       Chakwal
7  Lubaina       27   20                BS Chemistry  3.70  Azad Kashmir
8   Ayesha       11   19            BS Cybersecurity  3.80      Mianwali